#!/bin/bash
# Script 5: Open Source Manifesto Generator
# Author: Your Name | Course: Open Source Software
# Description: Asks user 3 questions and generates a
#              personal open source philosophy statement

# --- Welcome message ---
echo "================================"
echo " Open Source Manifesto Generator"
echo "================================"
echo "Answer three questions to generate your manifesto."
echo ""

# --- Ask user 3 questions and store answers in variables ---
read -p "1. Name one open-source tool you use every day: " TOOL
read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM
read -p "3. Name one thing you would build and share freely: " BUILD

# --- Get current date and username ---
DATE=$(date '+%d %B %Y')
USERNAME=$(whoami)

# --- Define output file name ---
OUTPUT="manifesto_$(whoami).txt"

# --- Compose the manifesto paragraph ---
echo "" 
echo "================================"
echo " Generating your manifesto..."
echo "================================"

# --- Write manifesto to file using >> ---
echo "Open Source Manifesto" > $OUTPUT
echo "Generated by: $USERNAME on $DATE" >> $OUTPUT
echo "================================" >> $OUTPUT
echo "" >> $OUTPUT
echo "I believe in the power of open source software." >> $OUTPUT
echo "Every day, I use $TOOL — a tool built freely by" >> $OUTPUT
echo "people who believed that $FREEDOM should belong to" >> $OUTPUT
echo "everyone, not just those who can afford it." >> $OUTPUT
echo "" >> $OUTPUT
echo "One day, I will build $BUILD and share it with" >> $OUTPUT
echo "the world for free, just as others have shared" >> $OUTPUT
echo "their work with me. This is the open source way." >> $OUTPUT
echo "" >> $OUTPUT
echo "Signed: $USERNAME" >> $OUTPUT
echo "Date  : $DATE" >> $OUTPUT

# --- Display the saved manifesto ---
echo ""
echo "--- Your Manifesto ---"
cat $OUTPUT
echo "================================"
echo "Manifesto saved to $OUTPUT"
